### ISSUE TITLE
Tela Novo Cadastro.

### ISSUE THREAD

**Issue by brunnovaz1** [Sasaestudo/pi-mobile#24]
Terá as opções de cadastrar novo cliente ou cuidador.

**Comment by Sasaestudo** [comment]
Pronto.

Versão final: 

![Image](https://github.com/Sasaestudo/pi-mobile/assets/128557335/9e5b4b7e-613d-4ce0-8c02-d68c3c89629c)

OBS.:  App Mobile do Cuidador: dispensado - Tela Novo Cadastro do cuidador - . Implementação postergada.
