### ISSUE TITLE
Tela Recuperar senha.

### ISSUE THREAD

**Issue by brunnovaz1** [Sasaestudo/pi-mobile#25]
Usuário pode digitar o e-mail e recuperar a senha.

**Comment by Larysmo** [comment]
![Image](https://github.com/Sasaestudo/pi-mobile/assets/128557290/b41b3d78-c3fb-4764-b542-2fa98aa11702)



![Image](https://github.com/Sasaestudo/pi-mobile/assets/128557290/174381b7-3d73-45b8-b615-74610d156348)

**Comment by Sasaestudo** [comment]
>  Versão final:

![Image](https://github.com/Sasaestudo/pi-mobile/assets/128557335/a6ac6f8a-993c-475a-9124-87ee248a40f9)

**Comment by Sasaestudo** [comment]
Concluído.

**Comment by Sasaestudo** [comment]
Okay
