### ISSUE TITLE
Tela principal App.

### ISSUE THREAD

**Issue by brunnovaz1** [Sasaestudo/pi-mobile#26]
Tela apresentará a agenda, conterá o menu, botões sair e ajuda.

**Comment by Sasaestudo** [comment]
Pronto.

Versão final:



![Image](https://github.com/Sasaestudo/pi-mobile/assets/128557335/a599ec36-04eb-4af2-bfcc-8936d1e84a5b)





![Image](https://github.com/Sasaestudo/pi-mobile/assets/128557335/e46f4248-3850-4d81-bff2-d75fb27438e1)





Botão ajuda  excluído da versão final do projeto.
