### ISSUE TITLE
Menu

### ISSUE THREAD

**Issue by brunnovaz1** [Sasaestudo/pi-mobile#27]
Menu presente em todas telas após o login do usuário.

**Comment by Sasaestudo** [comment]
Concluído.

Versão final: 

![Image](https://github.com/Sasaestudo/pi-mobile/assets/128557335/c2257d62-9452-4072-85c8-076ed0dfc5a1)



![Image](https://github.com/Sasaestudo/pi-mobile/assets/128557335/1ce7e3d0-48d1-44e5-8f35-fedd8c60f823)



![Image](https://github.com/Sasaestudo/pi-mobile/assets/128557335/e65cdcda-4e91-41ef-a6f8-6cbd4168a5f7)

**Comment by Sasaestudo** [comment]
Pronto.
