### ISSUE TITLE
Botão Sair

### ISSUE THREAD

**Issue by brunnovaz1** [Sasaestudo/pi-mobile#28]
Presente em todas telas após login.

**Comment by Sasaestudo** [comment]
Versão final com todas as telas com botão SAIR  (->).

![Image](https://github.com/Sasaestudo/pi-mobile/assets/128557335/114d8c30-2be5-4a05-a011-f7979fe82f27)



![Image](https://github.com/Sasaestudo/pi-mobile/assets/128557335/b5bb3a24-4874-419d-9ea0-5c0863447126)



![Image](https://github.com/Sasaestudo/pi-mobile/assets/128557335/eb1f2945-f976-4987-ade5-ef6011a4e838)
