### ISSUE TITLE
Tela Sobre

### ISSUE THREAD

**Issue by brunnovaz1** [Sasaestudo/pi-mobile#29]
Dúvidas e  contatos .

**Comment by Larysmo** [comment]
Tela Sobre - App

![Image](https://github.com/Sasaestudo/pi-mobile/assets/128557290/d807fcc5-6ad8-4d76-a5c9-4c52b6adf282)



![Image](https://github.com/Sasaestudo/pi-mobile/assets/128557290/15caa508-d7f4-4de0-88ce-f4ce841113dd)

**Comment by Sasaestudo** [comment]
Tela excluída do projeto.
