### ISSUE TITLE
Elaboração Protótipo Figma.

### ISSUE THREAD

**Issue by brunnovaz1** [Sasaestudo/pi-mobile#32]
Protótipo com as funcionalidades para apresentação ao cliente.

**Comment by Larysmo** [comment]
Protótipo App - Tutor

https://www.figma.com/proto/c7BZBsoKR53f45RUH0uNqY/Esquema-Pet-Sitter-App?type=design&node-id=1-2&t=rx4H0ljtezymsBk4-0&scaling=min-zoom&starting-point-node-id=1%3A120&show-proto-sidebar=1


Protótipo App - Pet Sitter

https://www.figma.com/proto/c7BZBsoKR53f45RUH0uNqY/Esquema-Pet-Sitter-App?type=design&node-id=1-2&t=rx4H0ljtezymsBk4-0&scaling=min-zoom&starting-point-node-id=75%3A693&show-proto-sidebar=1

**Comment by Sasaestudo** [comment]
App Mobile do Cuidador: dispensado. Implementação postergada.
