### ISSUE TITLE
Tela Cadastro Solicitação

### ISSUE THREAD

**Issue by brunnovaz1** [Sasaestudo/pi-mobile#33]
Cliente preenche data, seleciona pet e pode digitar informação.

**Comment by Sasaestudo** [comment]
Pronto.



Excluída onde cliente pode digitar informação adicional.



![Image](https://github.com/Sasaestudo/pi-mobile/assets/128557335/c9621c0c-f20b-4086-a76b-ebe094eb5bc5)
