### ISSUE TITLE
Tela Solicitar Serviço - Lista cuidadores.

### ISSUE THREAD

**Issue by brunnovaz1** [Sasaestudo/pi-mobile#38]
Lista para que o cliente escolha um cuidador.

**Comment by brunnovaz1** [comment]
Cuidadores disponíveis em lista;

**Comment by Sasaestudo** [comment]
Pronto.





![Image](https://github.com/Sasaestudo/pi-mobile/assets/128557335/d040695d-496a-4e22-a83c-e127e3d82881)
