### ISSUE TITLE
Tela Agenda - Botão Cancelar.

### ISSUE THREAD

**Issue by brunnovaz1** [Sasaestudo/pi-mobile#39]
Botão para cancelar solicitação confirmada ou pendente.

**Comment by Sasaestudo** [comment]
Pronto.

Botão Cancelar ou alterado para "excluir" e fina na tela "Home" todas os agendamento confirmados, veja: 


![Image](https://github.com/Sasaestudo/pi-mobile/assets/128557335/b80c077e-cd28-4883-9c13-85ee07f499ed)
