### ISSUE TITLE
Tela Perfil - Dados

### ISSUE THREAD

**Issue by brunnovaz1** [Sasaestudo/pi-mobile#40]
Criar componente para exibir dados.

**Comment by Larysmo** [comment]
Edição Tutor e Pet

![Image](https://github.com/Sasaestudo/pi-mobile/assets/128557290/15f7ed03-b37d-47b3-97dc-12413a274e65)
![Image](https://github.com/Sasaestudo/pi-mobile/assets/128557290/35d4c260-5fbf-4122-acd1-8f4d1cedd5d4)
![Image](https://github.com/Sasaestudo/pi-mobile/assets/128557290/209251d6-d8a0-419c-a53b-828c65ef6f3f)
![Image](https://github.com/Sasaestudo/pi-mobile/assets/128557290/6176edef-7af4-49a7-a7e0-7ed03609e452)

**Comment by Larysmo** [comment]
Edição Pet SItter

![Image](https://github.com/Sasaestudo/pi-mobile/assets/128557290/f36e9546-4cb1-4141-9108-346826697840)
![Image](https://github.com/Sasaestudo/pi-mobile/assets/128557290/43d07029-feba-47da-bc4f-2b208bc0fd24)

**Comment by Sasaestudo** [comment]
Pronto.

Versão final: 

![Image](https://github.com/Sasaestudo/pi-mobile/assets/128557335/c97f5c06-ed15-47ff-bbc0-2d48d49fd74d)




OBS.:  App Mobile do Cuidador: dispensado - Tela Novo Cadastro do cuidador - . Implementação postergada.
