### ISSUE TITLE
Agenda Serviço(s) Pendente(s)

### ISSUE THREAD

**Issue by brunnovaz1** [Sasaestudo/pi-mobile#43]
Exibe solicitações feitas por clientes aguardando aceitação do cuidador.

**Comment by Larysmo** [comment]
![Image](https://github.com/Sasaestudo/pi-mobile/assets/128557290/e9157b30-d536-40f5-81ae-5f8c733693fd)
![Image](https://github.com/Sasaestudo/pi-mobile/assets/128557290/b27f0694-4581-4e61-9b65-2485b5fd95e8)
![Image](https://github.com/Sasaestudo/pi-mobile/assets/128557290/b9f2081e-c50e-4a7f-858c-06dccd50be04)
![Image](https://github.com/Sasaestudo/pi-mobile/assets/128557290/b500e9f3-8970-4ec9-b521-549fe9633d73)

**Comment by Sasaestudo** [comment]
App Mobile do Cuidador: dispensado. Implementação postergada.

**Comment by Sasaestudo** [comment]
Dispensado o perfil do CUIDADOR.
