### ISSUE TITLE
Protótipo Figma Estático

### ISSUE THREAD

**Issue by Sasaestudo** [Sasaestudo/pi-mobile#48]
Protótipo estático de telas.

**Comment by Larysmo** [comment]
Esquema de telas estático app PetSitter e AppTutor do MeuPetFeliz

https://www.figma.com/file/c7BZBsoKR53f45RUH0uNqY/Esquema-Pet-Sitter-App?type=design&node-id=1%3A2&mode=design&t=rx4H0ljtezymsBk4-1
