### ISSUE TITLE
Tela cadastro

### ISSUE THREAD

**Issue by brunnovaz1** [Sasaestudo/pi-mobile#50]

**Comment by Larysmo** [comment]
![Image](https://github.com/Sasaestudo/pi-mobile/assets/128557290/d43c918a-d2dc-4631-b482-9ca69efbb71f)



![Image](https://github.com/Sasaestudo/pi-mobile/assets/128557290/abd24d2c-bedc-406f-95c6-9e07ecfd9618)
![Image](https://github.com/Sasaestudo/pi-mobile/assets/128557290/1b64ed9b-27c7-4b7d-a83d-b776aa3e7403)
