### ISSUE TITLE
Tela recuperar senha.

### ISSUE THREAD

**Issue by brunnovaz1** [Sasaestudo/pi-mobile#51]

**Comment by Larysmo** [comment]
![Image](https://github.com/Sasaestudo/pi-mobile/assets/128557290/a186e5f1-d732-4cbb-9b2b-845066dd0c0e)
![Image](https://github.com/Sasaestudo/pi-mobile/assets/128557290/379377e2-6121-4dc2-a51e-7139aa4aca06)



![Image](https://github.com/Sasaestudo/pi-mobile/assets/128557290/36bd2ea5-c403-4775-a6a6-0c42ca8c9333)
![Image](https://github.com/Sasaestudo/pi-mobile/assets/128557290/3fd9e120-cb41-4fe7-b475-f8faabc54650)

**Comment by Sasaestudo** [comment]
Pronto.


![Image](https://github.com/Sasaestudo/pi-mobile/assets/128557335/009236c3-403e-4bda-8e72-05dea8d568bb)
