### ISSUE TITLE
Tela inicial - Cuidador

### ISSUE THREAD

**Issue by brunnovaz1** [Sasaestudo/pi-mobile#52]
Contem as solicitações Pendentes.

**Comment by Larysmo** [comment]
![Image](https://github.com/Sasaestudo/pi-mobile/assets/128557290/c5ba5933-137b-4e0d-a78e-faedf6c1d1ec)

**Comment by Sasaestudo** [comment]
App Mobile do Cuidador: dispensado. Implementação postergada.

**Comment by Sasaestudo** [comment]
Dispensado o perfil do CUIDADOR.
