### ISSUE TITLE
Tela Selecionar Cuidador - Perfil Cliente

### ISSUE THREAD

**Issue by brunnovaz1** [Sasaestudo/pi-mobile#54]

**Comment by Larysmo** [comment]
![Image](https://github.com/Sasaestudo/pi-mobile/assets/128557290/990eccd4-c198-4dff-8ef9-9d39c20c7fe7)
![Image](https://github.com/Sasaestudo/pi-mobile/assets/128557290/d0070ab5-7672-4a4b-baa1-f4065024ed4d)
