### ISSUE TITLE
Tela Aceitar Solicitação - Perfil Cuidador

### ISSUE THREAD

**Issue by brunnovaz1** [Sasaestudo/pi-mobile#55]

**Comment by Larysmo** [comment]
![Image](https://github.com/Sasaestudo/pi-mobile/assets/128557290/3e717e1f-44bb-405c-b902-684b45de6005)
![Image](https://github.com/Sasaestudo/pi-mobile/assets/128557290/3fa84f52-e28c-406f-9007-f8c6fa2c3b60)
![Image](https://github.com/Sasaestudo/pi-mobile/assets/128557290/d7c4b268-9afa-4fec-bc88-b58098c23551)
