### ISSUE TITLE
Tela cadastro Pet

### ISSUE THREAD

**Issue by brunnovaz1** [Sasaestudo/pi-mobile#56]

**Comment by Larysmo** [comment]
![Image](https://github.com/Sasaestudo/pi-mobile/assets/128557290/bbca8cdd-dcd2-4be5-913d-8c8279f2d714)
![Image](https://github.com/Sasaestudo/pi-mobile/assets/128557290/60a8e9ce-9fff-407c-a194-3fab29f6a43a)
