### ISSUE TITLE
Tela agendamentos - Perfil Cliente

### ISSUE THREAD

**Issue by brunnovaz1** [Sasaestudo/pi-mobile#57]

**Comment by Larysmo** [comment]
![Image](https://github.com/Sasaestudo/pi-mobile/assets/128557290/bd7dd275-db46-4961-ac1c-b786f604328b)



![Image](https://github.com/Sasaestudo/pi-mobile/assets/128557290/e23b8710-353d-4605-9e95-7372a9e593e4)
