### ISSUE TITLE
Tela Editar/Excluir perfil Cuidador

### ISSUE THREAD

**Issue by brunnovaz1** [Sasaestudo/pi-mobile#60]

**Comment by Larysmo** [comment]
![Image](https://github.com/Sasaestudo/pi-mobile/assets/128557290/2b8f79a8-32cc-402e-bafd-8e3b607290af)
![Image](https://github.com/Sasaestudo/pi-mobile/assets/128557290/8512add0-77df-4d24-858a-7c15eb7d1a37)
![Image](https://github.com/Sasaestudo/pi-mobile/assets/128557290/06c1a662-50a2-405f-98ed-6372be4d63e4)
![Image](https://github.com/Sasaestudo/pi-mobile/assets/128557290/b789f176-2c5f-4c85-9994-6ff1792fa689)

**Comment by Sasaestudo** [comment]
OBS.:  App Mobile do Cuidador: dispensado - Tela Novo Cadastro do cuidador - . Implementação postergada.
