### ISSUE TITLE
Tela sobre.

### ISSUE THREAD

**Issue by brunnovaz1** [Sasaestudo/pi-mobile#61]

**Comment by Larysmo** [comment]
![Image](https://github.com/Sasaestudo/pi-mobile/assets/128557290/062bbb5a-76f6-45ae-9c62-5ce4b7b69e0e)



![Image](https://github.com/Sasaestudo/pi-mobile/assets/128557290/d4a0c11d-4abb-4bd2-9883-ca729c9bfc93)

**Comment by Sasaestudo** [comment]
Excluída do projeto tela SOBRE.
