### ISSUE TITLE
Tela Perfil - Dados Cliente

### ISSUE THREAD

**Issue by brunnovaz1** [Sasaestudo/pi-mobile#62]

**Comment by Larysmo** [comment]
![Image](https://github.com/Sasaestudo/pi-mobile/assets/128557290/e2ecf7b1-1255-494a-b71a-889cd95e03cf)

**Comment by Sasaestudo** [comment]
Pronto.

![Image](https://github.com/Sasaestudo/pi-mobile/assets/128557335/5b816bd2-65fd-4b84-bc19-e46959e51f02)
