### ISSUE TITLE
Tela Editar/Excluir perfil Pet

### ISSUE THREAD

**Issue by brunnovaz1** [Sasaestudo/pi-mobile#63]

**Comment by Larysmo** [comment]
![Confirmação exclusão perfil tutor](https://github.com/Sasaestudo/pi-mobile/assets/128557290/c0fa3372-625e-401b-90bf-58b5a5f35f03)
![Edita Pet](https://github.com/Sasaestudo/pi-mobile/assets/128557290/b976b472-9ec0-459b-9666-c964e0e35c82)
![Exclui Perfil Tutor](https://github.com/Sasaestudo/pi-mobile/assets/128557290/0040483e-7c72-4ff0-903c-2c98b5b51146)
![Finaliza edição](https://github.com/Sasaestudo/pi-mobile/assets/128557290/4ec5bb97-76b7-430a-b532-d2d823b8ba76)

**Comment by Larysmo** [comment]
![Finaliza edição](https://github.com/Sasaestudo/pi-mobile/assets/128557290/39b3119d-8fc4-433d-bf3c-318443d44280)

**Comment by Sasaestudo** [comment]
Pronto.



![Image](https://github.com/Sasaestudo/pi-mobile/assets/128557335/56232fe3-6ee6-4daf-9029-7403a11593a0)
