### ISSUE TITLE
Tela Cadastro - Formulário

### ISSUE THREAD

**Issue by brunnovaz1** [Sasaestudo/pi-mobile#64]

**Comment by Larysmo** [comment]
![Image](https://github.com/Sasaestudo/pi-mobile/assets/128557290/d14dbc78-fd67-4373-89bb-221eaeb37004)



![Image](https://github.com/Sasaestudo/pi-mobile/assets/128557290/4e721b98-256d-4b00-9c23-c3b0a8536e5d)
![Image](https://github.com/Sasaestudo/pi-mobile/assets/128557290/829c43ed-508d-493d-9e77-b08b1ebef245)

**Comment by Sasaestudo** [comment]
Pronto.


![Image](https://github.com/Sasaestudo/pi-mobile/assets/128557335/0d11f6ce-6b6d-40b3-b1c8-ec6a1604b846)
