### ISSUE TITLE
Tela de Solicitação Selecionada - Dados Cliente e Pet

### ISSUE THREAD

**Issue by brunnovaz1** [Sasaestudo/pi-mobile#80]
Componente que exibe dados do cliente e do Pet

**Comment by Larysmo** [comment]
![Avalia Solicitação - Pet Sitter](https://github.com/Sasaestudo/pi-mobile/assets/128557290/5b331264-a8f2-439f-a9f7-dc5e8459521b)
![Confirma Solicitação](https://github.com/Sasaestudo/pi-mobile/assets/128557290/5ada0771-bfd2-416b-bb53-d1a7038e128c)
![Recusa Solicitação](https://github.com/Sasaestudo/pi-mobile/assets/128557290/fa66cffc-6c9a-433f-8e1a-70d35b7657b5)

**Comment by Sasaestudo** [comment]
App Mobile do Cuidador: dispensado. Implementação postergada.

**Comment by Sasaestudo** [comment]
Dispensado o perfil CUIDADOR.
