### ISSUE TITLE
Tela Perfil - Dados Pet

### ISSUE THREAD

**Issue by brunnovaz1** [Sasaestudo/pi-mobile#93]

**Comment by Larysmo** [comment]
![Edita Pet](https://github.com/Sasaestudo/pi-mobile/assets/128557290/36f65fae-fc73-4662-b20e-3d21ab5932f1)
![Perfil Tutor](https://github.com/Sasaestudo/pi-mobile/assets/128557290/1f9d0d1e-00e2-4e2e-9fa3-4d674f5e473e)
