### ISSUE TITLE
Tela Cadastro Pet - Botão Cadastrar

### ISSUE THREAD

**Issue by brunnovaz1** [Sasaestudo/pi-mobile#98]

**Comment by Larysmo** [comment]
![Cadastra Pet](https://github.com/Sasaestudo/pi-mobile/assets/128557290/43f516c4-d655-4d8f-be5b-d1b78e567add)
![Perfil Tutor](https://github.com/Sasaestudo/pi-mobile/assets/128557290/75f6b63d-6950-4a00-9eca-292099560f34)
